# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSamples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSamples
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Reveal-SDK', '4'

  target 'RxSamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSamplesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
